import math
from FuncionesCrafteo import CantidadFabricar, MaterialSinFoco, MaterialConFoco, LlenadoDeLibros, CostoMaterial, PlataParaCraftear, TotalPlataGanadaPorElCrafteo, GastoEnLibros, TotalInvertir, GananciaLibros, GananciaFinal
from FuncionesCalcularLibros import Tela,Cuero,Placa

print('Calcular Crafteo de Ropa')
Ini = 2
while Ini ==2 :
    Craft = int(input('Que Deseas Craftear. \n 1)Cascos. \n 2)Chaquetas. \n 3)Sandalias. \n' ))
    if Craft == 1 or Craft == 2 or Craft == 3:
        if Craft == 1:
            print('Cascos')
            r = int(input('Que tipo de casco quieres craftear:\n 1)Cuero. \n 2)Placa. \n 3)Tela. \n'))
            if r == 1:
                print('Selecciono Capuchas')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r == 2:
                print('Selecciono Cascos')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r ==3:
                print('Selecciono Habitos')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            else:
                print('Valor Erroneo')
                exit()
        elif Craft == 2:
            print('Chaqutas') 
            r = int(input('Que tipo de chaquetas quieres craftear:\n 1)Cuero. \n 2)Placa. \n 3)Tela. \n'))
            if r == 1:
                print('Selecciono Chaquetas')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r == 2:
                print('Selecciono Pecheras')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r ==3:
                print('Selecciono Tunicas')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            else:
                print('Valor Erroneo')
                exit()
        elif Craft == 3:
            print('Sandalias')  
            r = int(input('Que tipo de sandalias quieres craftear:\n 1)Cuero. \n 2)Placa. \n 3)Tela. \n')) 
            if r == 1:
                print('Selecciono Zapatos')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r == 2:
                print('Selecciono Botas')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            elif r ==3:
                print('Selecciono Sandalias')
                foco = int(input('Cuanto te cuesta el foco por unidad: '))
                cantFoco = int(input('Cuanto foco tienes: '))
                cantItemxFoco =  CantidadFabricar(foco, cantFoco)
                cantMaterial = int(input('Cuanto material gasta x Item Sin devolucion: '))
                totalMaterialSFoco = MaterialSinFoco(cantItemxFoco, cantMaterial)
                tasaDev = int(input('Taza de Devolucion de Material: '))
                TotalMaterialCFoco = MaterialConFoco(totalMaterialSFoco, tasaDev)
                famaItem =int(input("Cuanta fama te da al craftear 1 item: ")) 
                famaLibro = int(input('Con cuanta fama se llena el libro: '))
                LlenadoLibros = LlenadoDeLibros(famaItem, famaLibro, cantItemxFoco)
                CostMaterial = int(input('Cual es el valor de Material Unitariamente: '))
                CstMaterial = CostoMaterial(CostMaterial, TotalMaterialCFoco)
                PCrafteo = int(input('Cual es el valor al crafear un item: '))
                PlataCraftear = PlataParaCraftear(cantItemxFoco, PCrafteo)
                ValItem = int(input('Cual es el valor del Item crafteado a vender: '))
                TotalPlataGanadaxElCrafteo = TotalPlataGanadaPorElCrafteo(cantItemxFoco, ValItem)
                PLibroVacio = int(input('Cuanto cuesta el libro Vacio: '))
                GastLibros = GastoEnLibros(LlenadoLibros, PLibroVacio)
                Inversion = TotalInvertir(CstMaterial, PlataCraftear, GastLibros)
                PreLibroLleno = int(input('Valor del Libro lleno: '))
                GanLibros = GananciaLibros(PreLibroLleno, LlenadoLibros, GastLibros)
                Total = GananciaFinal(TotalPlataGanadaxElCrafteo, GanLibros, Inversion)
                print('Tu inversion sera de: ',Inversion)
                print('Tu ganancia en Libros sera de: ',GanLibros)
                print('Tu ganancia final es de: ',Total)
            else:
                print('Valor Erroneo')
                exit()
        else:
            print('Variable Erronea')
    else:
        print('Variable Erronea')
    Ini = int(input('Deseas Salir: \n 1)Si. \n 2)No. \n'))
